# Run `docker build` from parent directory
# set base image (host OS)
FROM  python:3.8.13-buster

# set the working directory in the container
WORKDIR /app

# copy the content of the local directory to the working directory
COPY . /app

# install dependencies
RUN pip install -r requirements_dev.txt
RUN pip install -r requirements.txt

# install tools
RUN apt-get update && apt-get install git -y openssl -y build-essential -y

# Install Mongo
RUN apt-get systemctl -y 

RUN systemctl enable mongod  \
    systemctl start mongod \ 
    systemctl status mongod  \
    systemctl enable mongod

# Start Mongo
RUN systemctl enable mongod \
    systemctl start mongod